#
# Copyright (c) 2023 Volkswagen AG
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
version: "3"

services:
  miw:
    image: tractusx/managed-identity-wallet:0.4.0
    container_name: miw
    env_file:
      - ./miw/infrastructure.properties
    ports:
      - "0.0.0.0:8000:80"
      - "0.0.0.0:8090:8090"
    networks:
      - miw-net

  postgres:
    image: postgres:15.4-alpine
    container_name: postgres-miw
    environment:
      POSTGRES_DB: miw
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
      #    volumes:
      # use docker-compose down --volumes to kill db volume
      # only then, changes to the script are executed!
    #      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - miw-net

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    env_file:
      - ./miw/keycloak.properties
    environment:
      DB_SCHEMA: public
    command:
      - --verbose
      - start-dev
      - --import-realm
    volumes:
      - ./miw/keycloak-setup.json:/opt/keycloak/data/import/miw_test_realm.json
      - ./keycloak/supplier/Supplier-realm.json:/opt/keycloak/data/import/Supplier-realm.json
      - ./keycloak/supplier/Supplier-users-0.json:/opt/keycloak/data/import/Supplier-users-0.json
      - ./keycloak/customer/Customer-realm.json:/opt/keycloak/data/import/Customer-realm.json
      - ./keycloak/customer/Customer-users-0.json:/opt/keycloak/data/import/Customer-users-0.json
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - postgres
    networks:
      - miw-net
  vault:
    build: ./vault
    container_name: vault
    ports:
      - "0.0.0.0:8200:8200"
    environment:
      # token id may not contain prefix
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ADDR: http://vault:8200
      VAULT_PUT_SECRETS_DIR: ${VAULT_SECRETS_DIR}
      # ATTENTION: Non productive environment
      SKIP_SETCAP: true
      SKIP_CHOWN: true
    volumes:
      - ./vault/secrets:${VAULT_SECRETS_DIR}
    networks:
      - miw-net

  mock-util-service:
    build: ./iam-mock
    container_name: mock-util-service
    ports:
      - "0.0.0.0:8888:80"
    networks:
      - miw-net

  bdrs:
    image: tractusx/bdrs-server-memory:0.0.4
    container_name: bdrs
    env_file:
      - ./bdrs/application.properties
    environment:
      WEB_HTTP_PORT: 8580
      WEB_HTTP_PATH: /api
    ports:
      - "0.0.0.0:8580:8580"
      - "0.0.0.0:8581:8581"
      - "0.0.0.0:8582:8582"
    networks:
      - miw-net
networks:
  miw-net:
    name: miw-net
